import pandas as pd

# Description: This file contains the instructions that are used to clean the ingredients in the recipe
instructions = pd.DataFrame(
    {
        "Instruction": [
            "minced",
            "chopped",
            "diced",
            "blanched",
            "sliced",
            "grated",
            "peeled",
            "crushed",
            "melted",
            "mashed",
            "cut ",
            " cut",
            "condensed",
            "uncooked",
            "cooked",
            "cored",
            "shredded",
            "ground",
            "drained",
            "pounded",
            "rinsed",
            "dried",
            "dissolved",
            "divided",
            "scrubbed",
            "thawed",
            "quartered",
            "halved",
            "squeezed",
            "trimmed",
            "softened",
            "chilled",
            "to cover",
            "to coat",
            "to serve",
            "toasted",
            "to garnish" "to finish",
            "to decorate",
            "to dust",
            "to line",
            "to glaze",
            "to sprinkle",
            "to season",
            "to roll",
            "to grease",
            "to crush",
            "chilled",
            "julienned",
            "cubed",
            "torn into peieces",
            "roasted",
            "refrigerated",
            "rolled",
            "boiled",
            "baked",
            "beaten",
            "sifted",
            "skinned",
        ]
    }
)
